ALTER TABLE `Cloud` DROP FOREIGN KEY `Cloud_fk0`;

ALTER TABLE `Cloud` DROP FOREIGN KEY `Cloud_fk1`;

ALTER TABLE `Cloud` DROP FOREIGN KEY `Cloud_fk2`;

ALTER TABLE `Order` DROP FOREIGN KEY `Order_fk0`;

ALTER TABLE `Order` DROP FOREIGN KEY `Order_fk1`;

